<section id="section-banner">
  <div class="inner">
    <div id="banner-logo"></div>
    <h1 id="banner-title">HackTKU<span>2015</span></h1>
    <p id="banner-desc">2015/3/28-29，淡江大學</p>
    <a class="big-btn">Coming Soon</a>
  </div>
  <meta itemprop="name" content="HackTKU 2015">
  <meta itemprop="url" content="http://hacktku.org/2015/">
  <meta itemprop="startDate" content="2015-03-28T09:00:00+08:00">
  <meta itemprop="endDate" content="2015-03-29T18:00:00+08:00">
</section>